name: omnify-blog
services:
- name: backend
  source_dir: /backend
  github:
    repo: jaymahato10125/omnify_project
    branch: main
    deploy_on_push: true
  run_command: npm start
  build_command: npm install
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 8080
  env:
  - key: NODE_ENV
    value: production
  - key: PORT
    value: "8080"
  - key: JWT_SECRET
    value: omnify-blog-super-secure-jwt-production-key-2024
    type: SECRET
  - key: MONGODB_URI
    value: REPLACE_WITH_YOUR_MONGODB_ATLAS_CONNECTION_STRING
    type: SECRET

static_sites:
- name: frontend
  source_dir: /frontend
  github:
    repo: jaymahato10125/omnify_project
    branch: main
    deploy_on_push: true
  build_command: npm run build
  output_dir: /build
  index_document: index.html
  error_document: index.html
  routes:
  - path: /api
    preserve_path_prefix: true
  env:
  - key: REACT_APP_API_URL
    value: ${backend.PUBLIC_URL}
